evaluate: True
result_path: ./output/eval_ep10/text
tensorboard_path: ./output/eval_ep10/tensorboard
model_path: ./output/train3/saved_models
resume_path: ckpt_10.pth.tar
manual_seed: 1
print_freq: 20
dataset: "road"
experiment_name: "ralac_eval_ep10_road_test"

class_list: ["Red", "Amber", "Green",
"MovAway", "MovTow",
"Mov", "Rev", "Brake", "Stop",
"IncatLft", "IncatRht", "HazLit",
"TurLft", "TurRht",
"MovRht", "MovLft", "Ovtak",
"Wait2X", "XingFmLft", "XingFmRht", "Xing", "PushObj"]

data:
    train_split: 'train_3'
    val_split: 'test'

model:
    freeze_bn: True
    backbone:
        arch: slowfast50
        learnable: True
        pretrain:
            path: /home/jplu3502/road/acar_models/SLOWFAST_R50_K400.pth.tar
        kwargs:
            alpha: 4
            beta: 0.125
            fuse_only_conv: False
            fuse_kernel_size: 7
            slow_full_span: True
    neck:
        type: tube
        kwargs:
            bbox_jitter:
                num: 1
                scale: 0.075
            num_classes: 22
            multi_class: True
    head:
        type: tube_acar
        kwargs:
            width: 2304
            roi_spatial: 7
            num_classes: 22
            depth: 2

loss:
    type: sum_reduction_sigmoid_focal
    kwargs:
        pose_softmax: True

train:
    root_path: /home/jplu3502/road/rgb-images
    annotation_path: /home/jplu3502/road/road_trainval_v1.0.json
    class_idx_path: /home/jplu3502/road/class_name_gen_1.json
    batch_size: 2
    workers: 8
    max_norm: 10
    augmentation:
        spatial:
          - type: Scale
            kwargs:
                resize: 256
          - type: RandomHorizontalFlip
          - type: ToTensor
            kwargs:
                norm_value: 255.
          - type: Normalize
            kwargs:
                mean: [0.450, 0.450, 0.450]
                std: [0.225, 0.225, 0.225]
        temporal:
            type: TemporalCenterRetentionCrop
            kwargs:
                size: 64
                step: 2
        bbox_drop:
            type: RandomBBoxDrop
            kwargs:
                drop_rate: 0.00
    n_epochs: 1
    val_freq: 1
    save_freq: 1
    optimizer:
        type: SGD
        kwargs:
            momentum: 0.9
            weight_decay: 0.00001
            nesterov: True
    scheduler:
        type: step
        milestone_epochs: [12, 15, 18]
        lr_mults: [0.1, 0.1, 0.1]
        base_lr: 0.002
        warmup_lr: 0.016
        warmup_epochs: 1

val:
    root_path: /home/jplu3502/road/rgb-images
    annotation_path: /home/jplu3502/road/road_test_v1.0.json
    class_idx_path: /home/jplu3502/road/class_name_gen_1.json
    batch_size: 2
    workers: 8
    augmentation:
        spatial:
          - type: Scale
            kwargs:
                resize: 256
          - type: ToTensor
            kwargs:
                norm_value: 255.
          - type: Normalize
            kwargs:
                mean: [0.450, 0.450, 0.450]
                std: [0.225, 0.225, 0.225]
        temporal:
            type: TemporalCenterRetentionCrop
            kwargs:
                size: 64
                step: 2
    with_label: False
    eval_mAP:
        save_json: False
        labelmap: /home/jplu3502/road/road_test_v1.0.json
        groundtruth: /home/jplu3502/road/road_test_v1.0.json
